import Head from "next/head";
import { Sarabun } from "@next/font/google";
import r6Con from "../r6config/reg6.config.json";
import clsx from "clsx";
import MonthlyStat from "./MonthlyStat";
import MonthAverage from "./MonthAverage";

export const title_txt = Sarabun({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>{r6Con.reg6}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2
          className={clsx(
            "mt-5 text-xl text-center font-sarabun font-semibold",
            title_txt.className
          )}
        >
          {r6Con.header_txt}
        </h2>
      </div>
      <div
        className={clsx(
          "p-5 mt-5 ml-5 mr-5 border border-gray-400 rounded-sm cursor-pointer ",
          title_txt.className
        )}
      >
        <MonthlyStat />
      </div>
      <div
        className={clsx(
          "p-5 mt-5 ml-5 mr-5 border border-gray-400 rounded-sm cursor-pointer ",
          title_txt.className
        )}
      >
        <MonthAverage />
      </div>
    </>
  );
}
